project_id = "medatlas"

[api]
enabled = true
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
major_version = 17

[storage]
enabled = true

[auth]
enabled = true
site_url = "http://localhost:3016"
additional_redirect_urls = ["http://localhost:3016/**"]
